### ISSUE TITLE
Compare and pull issues

### ISSUE THREAD

**Issue by manuelgitgomes** [DanielCoelho112/AutoMec-AD#1]
After pushing the non pushed work, this "compare and pull" appeared and my pushed code does not appear. How can we solve this?

![Screenshot from 2021-01-20 10-20-08](https://user-images.githubusercontent.com/58152228/105161512-5e4efc00-5b09-11eb-9383-eca37c918595.png)

**Comment by DanielCoelho112** [comment]
Your work has been pushed successfully now, can I close the issue? @manuelgitgomes

**Comment by manuelgitgomes** [comment]
Sorry, it's now closed. Thank you.
