### ISSUE TITLE
Camera Proprieties

### ISSUE THREAD

**Issue by manuelgitgomes** [DanielCoelho112/AutoMec-AD#13]
What are our camera proprieties (height, angle and FOV) and/or where can I see them? I know it must be on one of the xacro files, but I don't remember which one.
I need those so I can have the dimensions on the pictures for a better warp on the vision code. Thank you.
![2021_03_30_0t9_Kleki](https://user-images.githubusercontent.com/58152228/113024171-5a310180-917e-11eb-92fd-699a13d599d3.png)
Thank you in advance.

**Comment by brunomonteiro98** [comment]
![KinectEsquema2](https://user-images.githubusercontent.com/58668014/113024509-5a2d0380-9176-11eb-9466-cf65c66fa2a3.png)

**Comment by DanielCoelho112** [comment]
@manuelgitgomes, I think what you want is the robot.urdf.xacro file. In this case, 0.59 meters is the height and 0.4 rad is the angle you are referring to.
The code is the following:

`  

     <joint name="camera_rgb_joint" type="fixed">

    <origin xyz="0.003 0.011 0.59" rpy="0 0.4 0"/>   

    <parent link="camera_link"/>

    <child link="camera_rgb_frame"/>

     </joint>
`

**Comment by manuelgitgomes** [comment]
Thank you @DanielCoelho112. This issue is now closed.
