### ISSUE TITLE
Find technichal drawings of Prometheus

### ISSUE THREAD

**Issue by manuelgitgomes** [DanielCoelho112/AutoMec-AD#183]
Find technical drawings of the RC car in order to model it fully.

**Comment by PedroMS3** [comment]
i can't find the drawings, i have sent an email to Traxxas  and their response was that "Unfortunately, our Engineering Department does not release any design drawings."
![image](https://user-images.githubusercontent.com/94935535/217924070-18aea398-0769-408c-a8ba-141378835810.png)

**Comment by PedroMS3** [comment]
It would be useful, if we could have acess to do the 3D models of the car's chassis, we should better discuss this in the next meeting (13/02/2023)!!!! It's not an emergency though...
