### ISSUE TITLE
Fix Step Up Regulator

### ISSUE THREAD

**Issue by manuelgitgomes** [DanielCoelho112/AutoMec-AD#194]
Out (?) capacitor connection is damaged, please find where it connects and shunt it.

**Comment by Carolf27** [comment]
![IMG_20230503_171406](https://user-images.githubusercontent.com/129117353/235985763-c5351479-4760-4744-8d20-b6155ed78680.jpg)
After finding out that the damaged connection was between the capacitor and out we reconnected the two as shown in the picture

**Comment by Carolf27** [comment]
Then we tested it out and it worked! :))
