### ISSUE TITLE
Improve Wiki documentation

### ISSUE THREAD

**Issue by andrefdre** [DanielCoelho112/AutoMec-AD#201]
General improvement to the wiki.

Adding controller installation step-by-step procedure.

Create a diagram with every component in the car, and it's interaction and what they are for. (examples: cameras servo motor arduino etc.)

Add electrical diagram to wiki.

**Comment by andrefdre** [comment]
I found out why the phone wasn't able to communicate with the car. Basically, the images in the wiki explain to set the joystick topic to android_input_dir but for it to work it should be cmd_vel and the button for velocity isn't used anymore.

I also added a section to the wiki with the electrical schematic.

**Comment by andrefdre** [comment]
Documentation to all the scripts should be implemented, adding description to all the functions and a general description of what the main code is for similar to:

"""
    Script for driving the car using a Deep-learning model.
    The model is loaded from a .pkl file and the image is obtained from a ROS topic.
    The model is loaded from the path specified in the parameter 'model_name'.
    The image is obtained from the topic specified in the parameter 'image_raw_topic'.
    The steering angle is published in the topic specified in the parameter 'model_steering_topic'.
    The model can be changed by publishing the name of the model in the topic '/set_model'.
"""

**Comment by Ze6000** [comment]
The users' guide for software installation needs to be tested on a computer recently installed with Linux to ensure its accuracy and correctness.
The simulation and operation of the real car was successful.
There is a bug encountered during the recording of the dataset in the real car.
The code provided after recording the dataset has not yet undergone testing.

**Comment by PedroMS3** [comment]
the wiki has been tested and aproved
