### ISSUE TITLE
Reform Teams Files

### ISSUE THREAD

**Issue by Ze6000** [DanielCoelho112/AutoMec-AD#202]
Several files within the Teams platform have become redundant and, therefore, necessitate a cleanup.
One suggestion is to consider creating a designated folder specifically for storing old designs, if necessary, but the removal of unnecessary files, including "Procedimento para ir para o EMA," is needed.

**Comment by PedroMS3** [comment]
Task successfully done, the old material has been put into dedicated folders on Teams
